In [129]:
#Car Matrix Generation
import pandas as pd
df = pd.read_csv("dataset-1.csv")
df.head()

   id_1  id_2  route   moto    car     rv   bus  truck
0   829   827      1   2.05   4.14   4.14  10.1   15.2
1   829   821      4   6.63  13.26  13.26  32.4   48.5
2   829   804      7  14.41  28.92  28.92  64.7   97.0
3   829   822      6   5.90  11.81  11.81  28.8   43.2
4   829   826      9   2.87   5.81   5.81  14.2   21.2

In [130]:
def generate_car_matrix(dataframe):
    dataframe1 = dataframe.pivot(index='id_1', columns="id_2", values='car').fillna(0)
    return dataframe1

In [131]:
generate_car_matrix(df)

id_2,801,802,803,804,805,806,807,808,809,821,822,823,824,825,826,827,829,830,831
id_1,,,,,,,,,,,,,,,,,,,
801,0.00,2.80,6.00,7.70,11.70,13.40,16.90,19.60,21.00,23.52,24.67,26.53,27.92,29.08,30.87,32.53,36.32,38.27,39.24
802,2.80,0.00,3.40,5.20,9.20,10.90,14.30,17.10,18.50,20.92,22.07,23.93,25.32,26.48,28.27,29.93,33.72,35.67,36.64
803,6.00,3.40,0.00,2.00,6.00,7.70,11.10,13.90,15.30,17.72,18.87,20.73,22.12,23.28,25.07,26.73,30.52,32.47,33.44
804,7.70,5.20,2.00,0.00,4.40,6.10,9.50,12.30,13.70,16.12,17.27,19.13,20.52,21.68,23.47,25.13,28.92,30.87,31.84
805,11.70,9.20,6.00,4.40,0.00,2.00,5.40,8.20,9.60,12.02,13.17,15.03,16.42,17.58,19.37,21.03,24.82,26.77,27.74
806,13.40,10.90,7.70,6.10,2.00,0.00,3.80,6.60,8.00,10.42,11.57,13.43,14.82,15.98,17.77,19.43,23.22,25.17,26.14
807,16.90,14.30,11.10,9.50,5.40,3.80,0.00,2.90,4.30,6.82,7.97,9.83,11.22,12.38,14.17,15.83,19.62,21.57,22.54
808,19.60,17.10,13.90,12.30,8.20,6.60,2.90,0.00,1.70,4.12,5.27,7.13,8.52,9.68,11.47,13.13,16.92,18.87,19.84
809,21.00,18.50,15.30,13.70,9.60,8.00,4.30,1.70,0.00,2.92,4.07,5.93,7.32,8.48,10.27,11.93,15.72,17.67,18.64
821,23.52,20.92,17.72,16.12,12.02,10.42,6.82,4.12,2.92,0.00,1.80,3.67,5.06,6.22,8.01,9.43,13.26,15.17,16.15
822,24.67,22.07,18.87,17.27,13.17,11.57,7.97,5.27,4.07,1.80,0.00,2.21,3.60,4.76,6.55,8.00,11.81,13.74,14.68
823,26.53,23.93,20.73,19.13,15.03,13.43,9.83,7.13,5.93,3.67,2.21,0.00,1.79,2.94,4.74,6.15,10.00,11.89,12.87
824,27.92,25.32,22.12,20.52,16.42,7.80,11.22,8.52,7.32,5.06,3.60,1.79,0.00,1.71,3.50,4.92,8.77,10.66,11.64
825,29.08,26.48,23.28,21.68,17.58,15.98,12.38,9.68,8.48,6.22,4.76,2.94,1.71,0.00,2.20,3.65,7.46,9.35,10.33
826,30.87,28.27,25.07,23.47,19.37,17.77,14.17,11.47,10.27,8.01,6.55,4.74,3.50,2.20,0.00,2.05,5.81,7.71,8.69
827,32.53,29.93,26.73,25.13,21.03,19.43,15.83,13.13,11.93,9.43,8.00,6.15,4.92,3.65,2.05,0.00,4.14,6.06,7.04
829,36.32,33.72,30.52,28.92,24.82,23.22,19.62,16.92,15.72,13.26,11.81,10.00,21.40,7.46,5.81,4.14,0.00,2.38,3.36
830,38.27,35.67,32.47,30.87,26.77,25.17,21.57,18.87,17.67,15.17,13.74,11.89,10.66,0.00,7.71,6.06,2.38,0.00,1.39
831,39.24,36.64,33.44,31.84,27.74,26.14,22.54,19.84,18.64,16.15,14.68,12.87,11.64,10.33,8.69,7.04,3.36,1.39,0.00

In [132]:
#Car Type Count Calculation
def get_type_count(dataframe):
    
    def categorize_value(value):
        if value <= 15:
            return 'Low'
        elif 15 <= value < 25:
            return 'Medium'
        else:
            return 'High'
        
    df['car_type'] = df['car'].apply(lambda x: categorize_value(x))
    value_counts = df['car_type'].value_counts()
    sorted_dict = dict(sorted(value_counts.items()))
    return sorted_dict

In [133]:
get_type_count(df)

{'High': 56, 'Low': 196, 'Medium': 89}

In [134]:
#Bus Count Index Retrieval
def get_bus_indexes(df):
    mean_bus_value = df['bus'].mean()
    indices = df[df['bus'] > 2 * mean_bus_value].index.tolist()
    indices.sort()
    
    return indices

In [135]:
get_bus_indexes(df)

[2,
 7,
 12,
 17,
 25,
 30,
 54,
 64,
 70,
 97,
 144,
 145,
 149,
 154,
 160,
 201,
 206,
 210,
 215,
 234,
 235,
 245,
 250,
 309,
 314,
 319,
 322,
 323,
 334,
 340]

In [149]:
def filter_routes(dataframe):
    avg_truck_route = df.groupby('route')['truck'].mean()
    routes = avg_truck_route[avg_truck_route > 7].index.tolist()
    routes.sort()
    
    return routes

In [150]:
filter_routes(df)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [151]:
#Matrix Value Modification
def multiply_matrix(dataframe):
    result = generate_car_matrix(dataframe)
    condition = lambda x: x * 0.75 if x > 20 else x*1.25
    result_df = result.applymap(condition)
    return result_df

In [152]:
multiply_matrix(df)

id_2,801,802,803,804,805,806,807,808,809,821,822,823,824,825,826,827,829,830,831
id_1,,,,,,,,,,,,,,,,,,,
801,0.0000,3.5000,7.5000,9.6250,14.6250,16.7500,21.1250,24.5000,15.7500,17.6400,18.5025,19.8975,20.9400,21.8100,23.1525,24.3975,27.2400,28.7025,29.4300
802,3.5000,0.0000,4.2500,6.5000,11.5000,13.6250,17.8750,21.3750,23.1250,15.6900,16.5525,17.9475,18.9900,19.8600,21.2025,22.4475,25.2900,26.7525,27.4800
803,7.5000,4.2500,0.0000,2.5000,7.5000,9.6250,13.8750,17.3750,19.1250,22.1500,23.5875,15.5475,16.5900,17.4600,18.8025,20.0475,22.8900,24.3525,25.0800
804,9.6250,6.5000,2.5000,0.0000,5.5000,7.6250,11.8750,15.3750,17.1250,20.1500,21.5875,23.9125,15.3900,16.2600,17.6025,18.8475,21.6900,23.1525,23.8800
805,14.6250,11.5000,7.5000,5.5000,0.0000,2.5000,6.7500,10.2500,12.0000,15.0250,16.4625,18.7875,20.5250,21.9750,24.2125,15.7725,18.6150,20.0775,20.8050
806,16.7500,13.6250,9.6250,7.6250,2.5000,0.0000,4.7500,8.2500,10.0000,13.0250,14.4625,16.7875,18.5250,19.9750,22.2125,24.2875,17.4150,18.8775,19.6050
807,21.1250,17.8750,13.8750,11.8750,6.7500,4.7500,0.0000,3.6250,5.3750,8.5250,9.9625,12.2875,14.0250,15.4750,17.7125,19.7875,24.5250,16.1775,16.9050
808,24.5000,21.3750,17.3750,15.3750,10.2500,8.2500,3.6250,0.0000,2.1250,5.1500,6.5875,8.9125,10.6500,12.1000,14.3375,16.4125,21.1500,23.5875,24.8000
809,15.7500,23.1250,19.1250,17.1250,12.0000,10.0000,5.3750,2.1250,0.0000,3.6500,5.0875,7.4125,9.1500,10.6000,12.8375,14.9125,19.6500,22.0875,23.3000
821,17.6400,15.6900,22.1500,20.1500,15.0250,13.0250,8.5250,5.1500,3.6500,0.0000,2.2500,4.5875,6.3250,7.7750,10.0125,11.7875,16.5750,18.9625,20.1875
822,18.5025,16.5525,23.5875,21.5875,16.4625,14.4625,9.9625,6.5875,5.0875,2.2500,0.0000,2.7625,4.5000,5.9500,8.1875,10.0000,14.7625,17.1750,18.3500
823,19.8975,17.9475,15.5475,23.9125,18.7875,16.7875,12.2875,8.9125,7.4125,4.5875,2.7625,0.0000,2.2375,3.6750,5.9250,7.6875,12.5000,14.8625,16.0875
824,20.9400,18.9900,16.5900,15.3900,20.5250,9.7500,14.0250,10.6500,9.1500,6.3250,4.5000,2.2375,0.0000,2.1375,4.3750,6.1500,10.9625,13.3250,14.5500
825,21.8100,19.8600,17.4600,16.2600,21.9750,19.9750,15.4750,12.1000,10.6000,7.7750,5.9500,3.6750,2.1375,0.0000,2.7500,4.5625,9.3250,11.6875,12.9125
826,23.1525,21.2025,18.8025,17.6025,24.2125,22.2125,17.7125,14.3375,12.8375,10.0125,8.1875,5.9250,4.3750,2.7500,0.0000,2.5625,7.2625,9.6375,10.8625
827,24.3975,22.4475,20.0475,18.8475,15.7725,24.2875,19.7875,16.4125,14.9125,11.7875,10.0000,7.6875,6.1500,4.5625,2.5625,0.0000,5.1750,7.5750,8.8000
829,27.2400,25.2900,22.8900,21.6900,18.6150,17.4150,24.5250,21.1500,19.6500,16.5750,14.7625,12.5000,16.0500,9.3250,7.2625,5.1750,0.0000,2.9750,4.2000
830,28.7025,26.7525,24.3525,23.1525,20.0775,18.8775,16.1775,23.5875,22.0875,18.9625,17.1750,14.8625,13.3250,0.0000,9.6375,7.5750,2.9750,0.0000,1.7375
831,29.4300,27.4800,25.0800,23.8800,20.8050,19.6050,16.9050,24.8000,23.3000,20.1875,18.3500,16.0875,14.5500,12.9125,10.8625,8.8000,4.2000,1.7375,0.0000

In [153]:
#Time Check
df2 = pd.read_csv("dataset-2.csv")
df2.head()

,id,name,id_2,startDay,startTime,endDay,endTime,able2Hov2,able2Hov3,able3Hov2,able3Hov3,able5Hov2,able5Hov3,able4Hov2,able4Hov3
0,1040000,Montgomery,-1,Monday,05:00:00,Wednesday,10:00:00,3.0,3.0,-1.0,-1,3,3,3,3
1,1040010,Black,-1,Monday,10:00:00,Friday,15:00:00,6.0,6.0,-1.0,-1,6,6,6,6
2,1040020,Emerald,-1,Thursday,15:00:00,Friday,19:00:00,3.0,3.0,-1.0,-1,3,3,3,3
3,1040030,Foley,-1,Monday,19:00:00,Friday,23:59:59,6.0,6.0,-1.0,-1,6,6,6,6
4,1050000,Whittier,1050001,Saturday,00:00:00,Sunday,23:59:59,6.0,6.0,NaN,-1,6,6,6,6

In [158]:
df3 = pd.read_csv('dataset-3.csv')
df3.head()

   id_start   id_end  distance
0   1001400  1001402       9.7
1   1001402  1001404      20.2
2   1001404  1001406      16.0
3   1001406  1001408      21.7
4   1001408  1001410      11.1

In [172]:
def calculate_distance_matrix(dataframe):
    distance_matrix = pd.DataFrame(index=df['id_start'].unique(), columns=df['id_end'].unique(), dtype=float)
    distance_matrix.values[[range(len(distance_matrix))]*2] = 0
    
    for _, row in df.iterrows():
        start_id, end_id = row['id_start'], row['id_end']

        distance_matrix.loc[start_id, end_id] = row['distance']
        distance_matrix.loc[end_id, start_id] = row['distance']

    for id_ in distance_matrix.index:
        for other_id in distance_matrix.columns:
            if id_ != other_id and pd.isna(distance_matrix.loc[id_, other_id]):
                cumulative_distance = distance_matrix.loc[id_].add(distance_matrix.loc[:, other_id])
                distance_matrix.loc[id_, other_id] = cumulative_distance[other_id]
                distance_matrix.loc[other_id, id_] = cumulative_distance[id_]

    return distance_matrix.fillna(0)

In [174]:
 calculate_distance_matrix(df3)

<ipython-input-173-baf230b7a946>:8: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  distance_matrix.values[[range(len(distance_matrix))]*2] = 0

,1001402,1001404,1001406,1001408,1001410,1001412,1001414,1001416,1001418,1001420,...,1001458,1001460,1001461,1001462,1001464,1001466,1001468,1001470,1001472,1001400
1001400,9.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001402,NaN,20.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.7
1001404,20.2,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001406,NaN,16.0,NaN,21.7,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001408,NaN,NaN,21.7,NaN,11.1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001410,NaN,NaN,NaN,11.1,NaN,15.6,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001412,NaN,NaN,NaN,NaN,15.6,NaN,18.2,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001414,NaN,NaN,NaN,NaN,NaN,18.2,NaN,13.2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001416,NaN,NaN,NaN,NaN,NaN,NaN,13.2,NaN,13.6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.6,NaN,12.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001440,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001488,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1004355,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,5.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001460,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,5.1,0.0,12.8,17.9,NaN,NaN,NaN,NaN,NaN,NaN
1001461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,12.8,0.0,5.1,NaN,NaN,NaN,NaN,NaN,NaN
1001462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,17.9,5.1,0.0,26.7,NaN,NaN,NaN,NaN,NaN
1001464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,26.7,0.0,8.5,NaN,NaN,NaN,NaN
1001466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.5,0.0,10.7,NaN,NaN,NaN
1001468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.7,0.0,10.6,NaN,NaN
1001470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10.6,0.0,16.0,NaN
1001437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1001472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN